### ISSUE TITLE
shared component react-native-web 

### ISSUE THREAD

**Issue by nicholasess** [FotonTech/gigatron#12]
## This point is share components between web and mobile.

Sometimes we think about how to make an app with components make feel to share and what are the limitations where we can't use some items from UI.

all need to understand this, we can create components to replace Div to View, but don't replace camera of react-native to use webcam from browser.

My idea is to use this think to create the components and help other people with the boilerplate

**Comment by jaburcodes** [comment]
@nicholasess @gustavomaes whats the best option?

@brunolemos shared 90% of his FE code here: https://github.com/devhubapp/devhub

**Comment by nicholasess** [comment]
Yeah, we can use the codebase from devhub to add in boilerplace, not replace, just use the think for that

**Comment by jaburcodes** [comment]
https://github.com/devhubapp/devhub/blob/ef6824e42dc4aae28595952c56cf52b2ecf8f33e/packages/web/package.json#L27

**Comment by jaburcodes** [comment]
https://github.com/necolas/react-native-web looks like the best option. Twitter is using it.

**Comment by nicholasess** [comment]
but the react native web is the best of options to use in boilerplate, I don't know another lib that makes the same thing

**Comment by jaburcodes** [comment]
https://twitter.com/jabur_guilherme/status/1084961976185507840

**Comment by jaburcodes** [comment]
docz is using rn-web as well.

**Comment by nicholasess** [comment]
@jaburcodes Do you know the limitations from react-native-web? you don't use camera and other features from devices.

**Comment by jaburcodes** [comment]
We can't use anything that required native linking.

**Comment by jaburcodes** [comment]
the right way to do this is creating a `components` new package.

**Comment by nicholasess** [comment]
@jaburcodes yes, you are right

**Comment by jaburcodes** [comment]
@nicholasess feel free to open a PR. lets do this together.

**Comment by nicholasess** [comment]
@jaburcodes ok man
