### ISSUE TITLE
add tests, a lot of tests

### ISSUE THREAD

**Issue by jaburcodes** [FotonTech/gigatron#13]
__

**Comment by luizcieslak** [comment]
I'd like to make some tests to `server/` using [graphql-tools](https://github.com/apollographql/graphql-tools) and Jest. Is that ok?

**Comment by jaburcodes** [comment]
@luizcieslak that would be great! Thanks

**Comment by jaburcodes** [comment]
Thake this as an example: https://github.com/graphql/graphql-js/tree/master/src/__tests__
