### ISSUE TITLE
graphql-js + TS server

### ISSUE THREAD

**Issue by jaburcodes** [FotonTech/gigatron#3]

**Comment by jaburcodes** [comment]
doing

**Comment by luizcieslak** [comment]
Jabur, I'm willing to open a PR. Is there anything else you plan to implement in this part?

**Comment by jaburcodes** [comment]
Hey @luizcieslak yes!!

I wanna build a User Module/authentication. I think @gustavomaes is working on it.

**Comment by gustavomaes** [comment]
@jaburcodes Yes, I'm working on it.

**Comment by luizcieslak** [comment]
yes, let me know if you guys need help. Nice work btw!

**Comment by gustavomaes** [comment]
Hi @luizcieslak , feel free to help. At the moment we need tests and shared components (maybe somebody doing this already, you can check the issue)
